apiVersion: v1
kind: Service
metadata:
  name: event-register-monolithic-service
spec:
  selector:
    app: event-register-monolithic-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
